//! Shadow binary downloader.
//!
//! It downloads a pre-built archive and extracts `shadow[.exe]` from it. The
//! default archive is owned by the public Shadow satellite release
//! (amajorai/shadow); RYU_SHADOW_RELEASE_URL overrides it with a private,
//! pre-release or self-built archive.

use std::path::PathBuf;

use anyhow::{Context, Result};

use crate::sidecar::download_manager::{
    build_http_client, compute_sha256, extract_from_tar_gz, extract_from_zip, fetch_sibling_sha256,
    ryu_dir, sha256_sibling_url, ProgressCallback, VersionStore,
};

// ── Paths ──────────────────────────────────────────────────────────────────────

fn bin_path() -> PathBuf {
    let name = if cfg!(target_os = "windows") {
        "shadow.exe"
    } else {
        "shadow"
    };
    ryu_dir().join("bin").join(name)
}

// ── Release URL ────────────────────────────────────────────────────────────────
//
// WHERE THE SHADOW BINARY ON A USER MACHINE COMES FROM. Identical in shape to
// Ghost's — see `sidecar/tools/ghost/downloader.rs` for the long form.
//
// 1. The Shadow satellite release at github.com/amajorai/shadow is the public
//    binary owner. The read-only satellite mirror generated by
//    tools/mirror-satellites.sh (legacy group) from apps/shadow plus
//    crates/ghost/{shadow,core,eyes,hands,permissions} carries the complete
//    source closure. The satellite carries a dispatch-only release workflow
//    that builds Linux, macOS and Windows archives at the train tag. Shadow
//    remains version-locked with Ryu, while its binary assets stay owned by the
//    satellite repo.
//
// 2. The Ryu hub release — github.com/amajorai/ryu/releases — carries Core,
//    Gateway and app-sidecar assets. It intentionally does not build or stage
//    Shadow archives; the satellite workflow owns those assets and emits a
//    sibling .sha256 for every archive.
//
//    The private release workflow and the public overlay both leave Shadow
//    archives out. The satellite release workflow is therefore the authoritative
//    producer, and the hub's mirror-releases job does not copy these app assets.
//
//    The satellite matrix has three legs (linux-x86_64, macos-aarch64 and
//    windows-x86_64). A host outside that matrix receives a useful download
//    error rather than a bare 404.
//
//    `releases/latest/download` rather than a pinned tag, mirroring
//    `manifest_sidecar`: an older Core pulls the newest Shadow.
//
// 3. `RYU_SHADOW_RELEASE_URL` — the override. A FULL per-platform URL, not a base
//    directory (unlike `RYU_SIDECAR_RELEASE_BASE`). What it is FOR is pointing
//    this downloader at a private, pre-release, self-hosted or locally-built
//    archive instead of the satellite artifact — including on a platform the
//    matrix does not cover. The old claim that no public Shadow release repo
//    existed is no longer true.

/// Env knob carrying the FULL per-platform Shadow release archive URL (not a base
/// directory). Overrides the satellite default; see archive_url for the unset case.
const SHADOW_RELEASE_REPO: &str = "amajorai/shadow";
const SHADOW_RELEASE_URL_ENV: &str = "RYU_SHADOW_RELEASE_URL";

/// The release asset this host needs — `shadow-<os>-<arch>.<ext>`. Both the last
/// path segment of the satellite URL archive_url synthesizes and the name quoted in
/// `ensure_installed`'s download failure, so an operator knows exactly what
/// `RYU_SHADOW_RELEASE_URL` must point at and what CI must publish.
///
/// The `<os>-<arch>` slug is [`crate::update::platform_tag`], byte-identical to
/// the suffix every headless asset is staged under in `.github/workflows/
/// release.yml` (`linux-x86_64` / `macos-aarch64` / `windows-x86_64`). Derived
/// rather than tabulated: the `cfg`-table that used to live here emitted
/// `macos-arm64` / `linux-x64` / `windows-x64`, a naming convention nothing in
/// this repo publishes.
///
/// The extension is load-bearing: `ensure_installed` downloads an ARCHIVE and
/// extracts `shadow[.exe]` from it, so the publisher must ship an archive, not a
/// bare binary like `ryu-core-macos-aarch64`.
fn artifact_name() -> String {
    let ext = if cfg!(target_os = "windows") {
        "zip"
    } else {
        "tar.gz"
    };
    format!("shadow-{}.{ext}", crate::update::platform_tag())
}

/// Resolve the release archive URL for this platform: [`SHADOW_RELEASE_URL_ENV`]
/// verbatim when set and non-blank, otherwise the Shadow satellite release asset.
///
/// **Infallible on purpose** — a behaviour change. This used to return `Err` when
/// the env was unset, because the train had no public Shadow release owner. The
/// satellite now owns the archive, so refusing would leave a published artifact
/// permanently unreachable. The remaining unpublished-platform case is diagnosed
/// where the 404 surfaces, in
/// [`ShadowDownloader::ensure_installed`].
fn archive_url() -> String {
    if let Ok(url) = std::env::var(SHADOW_RELEASE_URL_ENV) {
        let url = url.trim();
        if !url.is_empty() {
            return url.to_owned();
        }
    }
    // Built from artifact_name() so the URL cannot carry a platform slug the
    // satellite release workflow does not stage assets under.
    format!(
        "https://github.com/{}/releases/latest/download/{}",
        SHADOW_RELEASE_REPO,
        artifact_name()
    )
}

// ── Archive integrity: the sibling `.sha256` ───────────────────────────────────
//
// Byte-for-byte the same reasoning as Ghost's — see the long form in
// `sidecar/tools/ghost/downloader.rs`. In short: the satellite release workflow
// emits a `<asset>.sha256` next to every staged asset, `ensure_installed` used to pass
// `sha256: None` and execute whatever bytes came back, and a published digest
// nothing verifies against is a shipped artifact that cannot take effect.
//
// HOISTED: the parser + fetcher that used to be duplicated here now live in
// `download_manager::{parse_sha256_digest, fetch_sibling_sha256, sha256_sibling_url}`,
// which is the hoist ghost's section comment asked for. The parser's unit tests
// moved with it. `manifest_sidecar::fetch_release_sha256` stays separate (it is
// `#[cfg(not(debug_assertions))]` and its `screen_https` is module-private).
//
// Best-effort rather than fail-closed, unlike `mirror/overlay/install.sh`:
// `RYU_SHADOW_RELEASE_URL` exists to point at self-built archives that have no
// sibling digest, and failing closed would make the documented override unusable.

// ── ShadowDownloader ───────────────────────────────────────────────────────────

pub struct ShadowDownloader {
    client: reqwest::Client,
    on_progress: Option<ProgressCallback>,
}

impl ShadowDownloader {
    pub fn new() -> Self {
        Self {
            client: build_http_client(),
            on_progress: None,
        }
    }

    pub fn with_progress(mut self, cb: ProgressCallback) -> Self {
        self.on_progress = Some(cb);
        self
    }

    /// Best-effort fetch of the archive's sibling `<url>.sha256`, for
    /// [`crate::downloads::DownloadSpec::sha256`] to verify the downloaded bytes
    /// against. `None` when the checksum is absent, unreachable or malformed.
    ///
    /// Only `https` URLs are followed: `RYU_SHADOW_RELEASE_URL` is arbitrary
    /// operator input, and a plaintext checksum fetched over `http` is rewritable
    /// by whoever rewrote the archive, so following it would be verification
    /// theatre. A non-https override downloads unverified (warned) instead.
    async fn fetch_release_sha256(&self, archive_url: &str) -> Option<String> {
        fetch_sibling_sha256(&self.client, archive_url).await
    }

    /// Ensure the Shadow binary is installed at `~/.ryu/bin/shadow`.
    ///
    /// The release archive downloads through the global [`DownloadCenter`] (#456)
    /// so it streams to disk and shows in the overlay; we then extract the binary
    /// from the downloaded archive and place it atomically.
    pub async fn ensure_installed(
        &self,
        downloads: &crate::downloads::DownloadCenter,
    ) -> Result<()> {
        let dest = bin_path();

        // Fast path: already installed with a matching checksum.
        let store = VersionStore::load();
        if dest.exists() {
            if let Some(stored) = store.installed_checksum("shadow") {
                let actual = compute_sha256(&dest).await?;
                if actual == stored {
                    tracing::info!("shadow already installed and checksum valid — skipping");
                    return Ok(());
                }
                tracing::warn!(
                    "shadow checksum mismatch (stored={stored} actual={actual}), re-downloading"
                );
            }
        }

        let url = archive_url();
        tracing::info!("downloading shadow binary from {url}");

        // Download the archive through the center to a deterministic temp dest
        // (so its own `.part`/resume works), then read it back to extract.
        let archive_ext = if cfg!(target_os = "windows") {
            "zip"
        } else {
            "tar.gz"
        };
        let archive_dest = ryu_dir().join("tmp").join(format!("shadow.{archive_ext}"));

        // Integrity: verify the ARCHIVE against the sibling `.sha256` the release
        // publishes. Scope matters — this digest covers the downloaded archive
        // (`DownloadSpec::dest`), NOT the `shadow` binary extracted from it, which
        // is hashed separately below and recorded in `versions.json` under the
        // `shadow` key. Two different values over two different byte ranges;
        // crossing them would invert the fast path.
        let sha256 = self.fetch_release_sha256(&url).await;
        if sha256.is_none() {
            tracing::warn!(
                "shadow: no usable .sha256 published at {} — downloading unverified",
                sha256_sibling_url(&url)
            );
        }

        let archive_path = downloads
            .download_blocking(crate::downloads::DownloadSpec {
                kind: crate::downloads::DownloadKind::Tool,
                role: crate::downloads::DownloadRole::Tool,
                label: "Shadow".to_string(),
                url: url.to_string(),
                dest: archive_dest,
                sha256,
                version_record: None,
            })
            .await
            // Name the likely cause at the point where a missing platform asset
            // becomes an HTTP 404, rather than leaving a bare transfer error.
            .with_context(|| {
                format!(
                    "downloading shadow archive from {url}. If this is a 404, the \
                     Shadow satellite publishes no `{}` — set {SHADOW_RELEASE_URL_ENV} to a \
                     self-built or pre-release archive for this platform, or build \
                     shadow from source (apps/shadow in the monorepo, or its public \
                     mirror github.com/amajorai/shadow)",
                    artifact_name()
                )
            })?;
        let archive_data = tokio::fs::read(&archive_path)
            .await
            .context("reading downloaded shadow archive")?;

        // Extract binary from the archive (blocking I/O on a thread-pool thread).
        let binary_name = if cfg!(target_os = "windows") {
            "shadow.exe"
        } else {
            "shadow"
        };
        let extracted = tokio::task::spawn_blocking(move || {
            #[cfg(target_os = "windows")]
            {
                extract_from_zip(&archive_data, binary_name)
            }
            #[cfg(not(target_os = "windows"))]
            {
                extract_from_tar_gz(&archive_data, binary_name)
            }
        })
        .await
        .context("spawn_blocking for archive extraction")??;

        // Write extracted binary atomically.
        if let Some(parent) = dest.parent() {
            tokio::fs::create_dir_all(parent).await?;
        }
        let atomic_tmp = dest.with_extension("tmp");
        tokio::fs::write(&atomic_tmp, &extracted)
            .await
            .with_context(|| format!("writing {}", atomic_tmp.display()))?;
        tokio::fs::rename(&atomic_tmp, &dest)
            .await
            .with_context(|| format!("rename {} → {}", atomic_tmp.display(), dest.display()))?;

        // Set executable bit on Unix.
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mut perms = std::fs::metadata(&dest)?.permissions();
            perms.set_mode(0o755);
            std::fs::set_permissions(&dest, perms)?;
        }

        // Compute checksum from in-memory bytes (avoids re-reading from disk).
        let checksum = {
            use sha2::{Digest, Sha256};
            let mut hasher = Sha256::new();
            hasher.update(&extracted);
            hex::encode(hasher.finalize())
        };
        let version = "latest"; // TODO: Get actual version from binary
        VersionStore::record_persisted("shadow", version, &checksum)
            .context("writing versions.json")?;

        // The extracted binary is in place; drop the temp archive.
        let _ = tokio::fs::remove_file(&archive_path).await;

        // Ensure PATH includes ~/.ryu/bin
        if let Err(e) = crate::sidecar::path_manager::PathManager::add_to_path() {
            tracing::warn!("Failed to add ~/.ryu/bin to PATH: {}", e);
        }

        tracing::info!("shadow installed at {}", dest.display());
        Ok(())
    }
}

impl Default for ShadowDownloader {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // `std::env::set_var` is process-global: these tests must not interleave with
    // each other. Mirrors the guard in the Ghost downloader's tests.
    static SHADOW_ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());
    fn lock_env() -> std::sync::MutexGuard<'static, ()> {
        SHADOW_ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner())
    }

    struct EnvGuard {
        prev: Option<String>,
    }
    impl EnvGuard {
        fn set(val: &str) -> Self {
            let prev = std::env::var(SHADOW_RELEASE_URL_ENV).ok();
            std::env::set_var(SHADOW_RELEASE_URL_ENV, val);
            Self { prev }
        }
        fn clear() -> Self {
            let prev = std::env::var(SHADOW_RELEASE_URL_ENV).ok();
            std::env::remove_var(SHADOW_RELEASE_URL_ENV);
            Self { prev }
        }
    }
    impl Drop for EnvGuard {
        fn drop(&mut self) {
            match &self.prev {
                Some(v) => std::env::set_var(SHADOW_RELEASE_URL_ENV, v),
                None => std::env::remove_var(SHADOW_RELEASE_URL_ENV),
            }
        }
    }

    #[test]
    fn bin_path_is_under_the_ryu_bin_dir() {
        let p = bin_path();
        assert_eq!(p.parent().and_then(|d| d.file_name()), Some("bin".as_ref()));
        assert!(
            p.file_name()
                .is_some_and(|n| n.to_string_lossy().starts_with("shadow")),
            "got: {}",
            p.display()
        );
    }

    #[test]
    fn artifact_name_uses_the_release_trains_platform_slug() {
        // Derived, not tabulated, so it cannot drift from the slug the release
        // workflow stages assets under — the drift that left `macos-arm64` here
        // next to a train publishing `macos-aarch64`.
        let name = artifact_name();
        assert!(name.starts_with("shadow-"), "got: {name}");
        assert!(
            name.contains(&crate::update::platform_tag()),
            "artifact name {name} must carry the release train's platform slug {}",
            crate::update::platform_tag()
        );
        // An ARCHIVE, because `ensure_installed` extracts a binary out of it.
        let ext = if cfg!(target_os = "windows") {
            ".zip"
        } else {
            ".tar.gz"
        };
        assert!(name.ends_with(ext), "got: {name}");
    }

    #[test]
    fn archive_url_defaults_to_the_shadow_satellite_release_asset() {
        // The satellite owns Shadow's platform archives; the hub release does not.
        let _lock = lock_env();
        let _g = EnvGuard::clear();
        let url = archive_url();
        assert_eq!(
            url,
            format!(
                "https://github.com/{}/releases/latest/download/{}",
                SHADOW_RELEASE_REPO,
                artifact_name()
            ),
            "got: {url}"
        );
        assert!(url.ends_with(&artifact_name()), "got: {url}");
        // `latest`, not a pinned tag — mirrors `manifest_sidecar`. See source 2.
        assert!(url.contains("/releases/latest/download/"), "got: {url}");
    }

    #[test]
    fn archive_url_uses_env_override_trimmed() {
        // The override still wins over the new default, and is used VERBATIM: it
        // carries a full URL, not a base to append `artifact_name()` to.
        let _lock = lock_env();
        let _g = EnvGuard::set("  https://mirror.test/shadow.tar.gz  ");
        assert_eq!(archive_url(), "https://mirror.test/shadow.tar.gz");
    }

    #[test]
    fn archive_url_blank_env_falls_back_to_the_satellite_default() {
        // A knob set to whitespace is unset, not an empty URL.
        let _lock = lock_env();
        let _g = EnvGuard::set("   ");
        assert!(archive_url().starts_with("https://github.com/"));
        assert!(archive_url().ends_with(&artifact_name()));
    }

    // ── sibling `.sha256` ─────────────────────────────────────────────────────
    //
    // Pure half only, deliberately: a test doing a live GET against the satellite is
    // green whenever GitHub is up and says nothing about whether we can parse what
    // the release actually publishes.

    // The PARSER's tests moved to `download_manager::sha256_sibling_tests` with the
    // parser itself. What stays here is shadow-specific: that the URL we actually
    // request is the sibling of shadow's own archive URL, and that shadow's wrapper
    // keeps the https-only rule.
    #[test]
    fn sha256_url_is_the_published_asset_plus_the_suffix() {
        // The workflow emits `<asset>.sha256` — an exact sibling, not a separate
        // SHASUMS manifest. Drift here silently downgrades every download to
        // unverified, so pin it against the URL we really request.
        let _lock = lock_env();
        let _g = EnvGuard::clear();
        let url = archive_url();
        assert_eq!(sha256_sibling_url(&url), format!("{url}.sha256"));
        assert!(
            sha256_sibling_url(&url).ends_with(".tar.gz.sha256") || cfg!(target_os = "windows")
        );
    }

    #[tokio::test]
    async fn fetch_release_sha256_refuses_non_https_urls() {
        // `RYU_SHADOW_RELEASE_URL` is operator input. Over plaintext the checksum is
        // rewritable by whoever rewrote the archive, so decline rather than perform
        // verification theatre — the caller then warns and downloads unverified,
        // which is at least honest. No network is touched: the scheme check returns
        // before a request is built.
        let d = ShadowDownloader::new();
        assert_eq!(
            d.fetch_release_sha256("http://mirror.test/s.tar.gz").await,
            None
        );
        assert_eq!(
            d.fetch_release_sha256("file:///tmp/shadow.tar.gz").await,
            None
        );
        assert_eq!(d.fetch_release_sha256("/tmp/shadow.tar.gz").await, None);
    }
}
