"use client";

import {
	createFileTreeIconResolver,
	getBuiltInSpriteSheet,
} from "@pierre/trees";
import { useId } from "react";

const COMPLETE_ICONS = { set: "complete", colored: true } as const;
const resolver = createFileTreeIconResolver(COMPLETE_ICONS);
const spriteSheet = getBuiltInSpriteSheet("complete");
const symbolCache = new Map<string, string>();

function getScopedSymbol(name: string, scopedName: string): string {
	const cached = symbolCache.get(name);
	const symbol =
		cached ??
		(() => {
			const start = spriteSheet.indexOf(`<symbol id="${name}"`);
			const end = spriteSheet.indexOf("</symbol>", start);
			if (start === -1 || end === -1) {
				return "";
			}
			return spriteSheet.slice(start, end + "</symbol>".length);
		})();
	if (cached === undefined) {
		symbolCache.set(name, symbol);
	}
	const scoped = symbol.replace(`id="${name}"`, `id="${scopedName}"`);
	return `<svg aria-hidden="true" width="0" height="0">${scoped}</svg>`;
}

/**
 * The same complete @pierre/trees file icon used by the workspace Files tree,
 * rendered in chat mentions, previews, change lists, and attachment rows.
 */
export function FileTypeIcon({
	className,
	path,
}: {
	className?: string;
	path: string;
}) {
	const instanceId = useId().replaceAll(":", "");
	const icon = resolver.resolveIcon("file-tree-icon-file", path);
	const symbolId = `${instanceId}-${icon.name}`;
	const scopedSymbol = getScopedSymbol(icon.name, symbolId);

	return (
		<span
			aria-hidden
			className={`inline-flex shrink-0${className ? ` ${className}` : ""}`}
		>
			<span
				className="pointer-events-none absolute size-0 overflow-hidden"
				// The symbol is generated by @pierre/trees from its bundled, static SVG.
				// It contains no user or network content.
				dangerouslySetInnerHTML={{ __html: scopedSymbol }}
			/>
			<svg className="size-full" viewBox={icon.viewBox ?? "0 0 16 16"}>
				<use href={`#${symbolId}`} />
			</svg>
		</span>
	);
}
