use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(std::env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let pstack_root = manifest_dir.join("../../../apps/skills/pstack/skills");
    let pstack_root = pstack_root
        .canonicalize()
        .expect("bundled pstack skills directory must exist");

    println!("cargo:rerun-if-changed={}", pstack_root.display());

    let mut skill_dirs = read_dirs(&pstack_root);
    skill_dirs.sort();
    assert!(
        !skill_dirs.is_empty(),
        "bundled pstack skills directory must contain skill directories"
    );

    let mut generated = String::from("// @generated by crates/core/skills/build.rs\n");

    for (index, skill_dir) in skill_dirs.iter().enumerate() {
        let id = skill_dir
            .file_name()
            .and_then(|name| name.to_str())
            .expect("bundled skill directory names must be valid UTF-8");
        let skill_md = skill_dir.join("SKILL.md");
        assert!(
            skill_md.is_file(),
            "bundled pstack skill `{id}` must contain SKILL.md"
        );

        let mut files = Vec::new();
        collect_files(skill_dir, &mut files);
        files.sort();

        let files_name = format!("PSTACK_SKILL_FILES_{index}");
        writeln!(generated, "static {files_name}: &[BuiltinFile] = &[").unwrap();
        for file in files {
            let relative = file
                .strip_prefix(skill_dir)
                .expect("skill resource must be below its skill directory")
                .to_string_lossy()
                .replace('\\', "/");
            let absolute = file.to_string_lossy().replace('\\', "/");
            assert!(
                !relative.split('/').any(|part| part == ".."),
                "bundled skill resource path may not escape its skill directory"
            );
            writeln!(
                generated,
                "    BuiltinFile {{ path: r#\"{relative}\"#, source: include_str!(r##\"{absolute}\"##) }},"
            )
            .unwrap();
            println!("cargo:rerun-if-changed={}", file.display());
        }
        generated.push_str("];\n");
    }
    generated.push_str("static PSTACK_SKILLS: &[BuiltinSkill] = &[\n");
    for (index, skill_dir) in skill_dirs.iter().enumerate() {
        let id = skill_dir
            .file_name()
            .and_then(|name| name.to_str())
            .expect("bundled skill directory names must be valid UTF-8");
        writeln!(
            generated,
            "    BuiltinSkill {{ id: r#\"{id}\"#, files: PSTACK_SKILL_FILES_{index} }},"
        )
        .unwrap();
    }
    generated.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    fs::write(out_dir.join("pstack_bundle.rs"), generated).expect("write generated pstack bundle");
}

fn read_dirs(root: &Path) -> Vec<PathBuf> {
    fs::read_dir(root)
        .expect("read bundled pstack skill directories")
        .map(|entry| {
            let entry = entry.expect("read bundled pstack skill directory entry");
            assert!(
                entry
                    .file_type()
                    .expect("read bundled pstack entry type")
                    .is_dir(),
                "bundled pstack skills must be directories"
            );
            entry.path()
        })
        .collect()
}

fn collect_files(dir: &Path, files: &mut Vec<PathBuf>) {
    let mut entries = fs::read_dir(dir)
        .expect("read bundled pstack skill resources")
        .map(|entry| entry.expect("read bundled pstack resource entry"))
        .collect::<Vec<_>>();
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        let file_type = entry
            .file_type()
            .expect("read bundled pstack resource entry type");
        if file_type.is_dir() {
            collect_files(&path, files);
        } else {
            assert!(
                file_type.is_file(),
                "bundled pstack skill resource must be a regular file: {}",
                path.display()
            );
            files.push(path);
        }
    }
}
